const stage=document.querySelector('#stage'),slider=document.querySelector('#yearSlider'),yearLabel=document.querySelector('#yearLabel'),eraLabel=document.querySelector('#eraLabel'),snapshotYear=document.querySelector('#snapshotYear'),snapshotCards=document.querySelector('#snapshotCards'),question=document.querySelector('#thinkingQuestion');
let currentYear=1945, dragging=false,startX=0,startYear=1945;
const typeNames={event:'重大事件',leader:'領導與政權',economy:'政經議題'};
const typeColors={event:'var(--event)',leader:'var(--leader)',economy:'var(--economy)'};
function era(y){if(y<1939)return'戰前危機累積';if(y<1943)return'全面戰爭擴張';if(y<1946)return'戰局逆轉與戰爭終結';if(y<1950)return'重建、分裂與冷戰成形';return'冷戰全球化';}
function build(){const world=document.createElement('div');world.className='world';Object.entries(REGIONS).forEach(([key,r])=>{const lane=document.createElement('section');lane.className=`lane ${key}`;lane.innerHTML=`<div class="lane-label"><strong>${r.icon}｜${r.name}</strong><small>${r.subtitle}</small></div><div class="axis"></div>`;for(let y=1935;y<=1955;y++){const mark=document.createElement('div');mark.className='year-mark';mark.style.left=`${70+(y-1935)*103}px`;if(y%5===0)mark.innerHTML=`<span>${y}</span>`;lane.append(mark)}EVENTS.filter(e=>e.region===key).forEach(e=>{const b=document.createElement('button');b.className='event-card';b.dataset.id=e.id;b.style.left=`${70+(e.year-1935)*103}px`;b.style.setProperty('--type',typeColors[e.type]);b.innerHTML=`<span class="date">${e.date} · ${typeNames[e.type]}</span><b>${e.title}</b>`;b.addEventListener('click',ev=>{ev.stopPropagation();openCard(e)});lane.append(b)});world.append(lane)});world.insertAdjacentHTML('beforeend','<div class="focus-beam"></div>');stage.append(world)}
function setYear(y){currentYear=Math.max(1935,Math.min(1955,Math.round(y)));slider.value=currentYear;yearLabel.textContent=currentYear;eraLabel.textContent=era(currentYear);snapshotYear.textContent=currentYear;document.querySelector('.world').style.left=`${-(currentYear-1945)*103}px`;document.querySelectorAll('.event-card').forEach(c=>{const e=EVENTS.find(x=>x.id===c.dataset.id),d=Math.abs(e.year-currentYear);c.classList.toggle('near',d===0);c.classList.toggle('far',d>3)});renderSnapshot();question.textContent=QUESTIONS[currentYear]||`請找出距離 ${currentYear} 最近的三洲事件，推測它們之間可能存在的因果或連動關係。`;}
function nearest(region){const list=EVENTS.filter(e=>e.region===region).sort((a,b)=>Math.abs(a.year-currentYear)-Math.abs(b.year-currentYear));return list[0]}
function renderSnapshot(){snapshotCards.innerHTML='';Object.keys(REGIONS).forEach(k=>{const exact=EVENTS.filter(e=>e.region===k&&e.year===currentYear),items=exact.length?exact:[nearest(k)];const d=document.createElement('article');d.className=`snapshot ${exact.length?'':'empty'}`;d.innerHTML=`<div class="region">${REGIONS[k].icon} ${REGIONS[k].name}${exact.length?'':` · 鄰近 ${items[0].year}`}</div>${items.slice(0,2).map(e=>`<h3>${e.title}</h3><p>${e.summary}</p>`).join('')}`;d.addEventListener('click',()=>openCard(items[0]));snapshotCards.append(d)})}
const dialog=document.querySelector('#cardDialog'),flip=document.querySelector('#flipCard');
function openCard(e){flip.classList.remove('flipped');document.querySelector('#modalRegion').textContent=`${REGIONS[e.region].icon}｜${REGIONS[e.region].name}`;document.querySelector('#modalType').textContent=typeNames[e.type];document.querySelector('#modalDate').textContent=e.date;document.querySelector('#modalTitle').textContent=e.title;document.querySelector('#modalSummary').textContent=e.summary;document.querySelector('#modalLeaders').innerHTML=e.leaders.map(x=>`<span>${x}</span>`).join('');document.querySelector('#modalContext').textContent=e.context;document.querySelector('#modalImpact').textContent=e.impact;document.querySelector('#modalSource').href=e.source;dialog.showModal()}
flip.addEventListener('click',()=>flip.classList.toggle('flipped'));flip.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip.classList.toggle('flipped')}});document.querySelector('#closeDialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
slider.oninput=e=>setYear(+e.target.value);document.querySelector('#prevYear').onclick=()=>setYear(currentYear-1);document.querySelector('#nextYear').onclick=()=>setYear(currentYear+1);document.querySelector('#resetBtn').onclick=()=>setYear(1945);
stage.addEventListener('wheel',e=>{e.preventDefault();setYear(currentYear+(e.deltaY>0?1:-1))},{passive:false});stage.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;startYear=currentYear;stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(dragging)setYear(startYear-(e.clientX-startX)/90)});stage.addEventListener('pointerup',()=>dragging=false);stage.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')setYear(currentYear-1);if(e.key==='ArrowRight')setYear(currentYear+1)});
const help=document.querySelector('#helpDialog');document.querySelector('#helpBtn').onclick=()=>help.showModal();document.querySelector('#closeHelp').onclick=()=>help.close();help.addEventListener('click',e=>{if(e.target===help)help.close()});
build();setYear(1945);
